<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>MergePool.Engine</RootNamespace>
    <AssemblyName>MergePool.Engine</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MergePool.Core\MergePool.Core.csproj" />
    <ProjectReference Include="..\MergePool.Ipc\MergePool.Ipc.csproj" />
    <ProjectReference Include="..\MergePool.Update\MergePool.Update.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MergePool.Engine.Tests" />
  </ItemGroup>

</Project>
