<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>MergePool.Ui</RootNamespace>
    <AssemblyName>MergePool</AssemblyName>
    <IsWindowsOnlyProject>true</IsWindowsOnlyProject>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\MergePool.ico</ApplicationIcon>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\MergePool.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MergePool.Ipc\MergePool.Ipc.csproj" />
  </ItemGroup>

</Project>
